name: "Release Workflow"

on:
  push:
    tags:
      - '*'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref_name }}"
  cancel-in-progress: true

jobs:
  release_notes:
    timeout-minutes: 30
    name: Create changelog on tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
