name: "Release Workflow"

on:
  push:
    tags:
      - 'v[0-9].[0-9]+.[0-9]+*'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref_name }}"
  cancel-in-progress: true

jobs:

  push_image:
    timeout-minutes: 30
    name: Push the image on release
    runs-on: ubuntu-latest
    steps:
        -   name: Checkout code
            uses: actions/checkout@v2
        -   name: Setup buildx
            id: buildx_setup
            uses: docker/setup-buildx-action@v1
            with:
                install: true
        -   run: |
                git describe --tags --long --dirt
                echo "git_commit=$(git describe --tags --long --dirty)" >> $GITHUB_ENV
                echo "build_date=$(date --rfc-3339=seconds)" >> $GITHUB_ENV
        -   name: Docker metadata
            id: meta
            uses: docker/metadata-action@v4
            with:
                tags: |
                    type=match,pattern=/^v?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
                    type=raw,enable=true,priority=200,value=${{ github.sha }},event=tag
                images: |
                  foo
        -   name: Build image
            uses: docker/build-push-action@v2
            with:
                context: ./
                file: .
                builder: ${{ steps.buildx_setup.outputs.name }}
                build-args: version=${{ env.version }}
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                cache-from: type=gha, scope=${{ github.workflow }}
                cache-to: type=gha, scope=${{ github.workflow }}, mode=max
